// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"
)

type Config struct {
	Clave string
	Valor string
}

type CuotasConfig struct {
	ID        int64
	Categoria string
	Monto     float64
}

type CuotasGenerada struct {
	ID             int64
	SocioID        int64
	Periodo        string
	MontoOriginal  float64
	MontoPendiente float64
	Estado         string
}

type Pagina struct {
	ID                 int64
	Titulo             string
	Slug               string
	Contenido          string
	Estado             string
	Visibilidad        string
	AutorID            int64
	FechaActualizacion time.Time
}

type Socio struct {
	ID              int64
	NumeroSocio     sql.NullString
	Nombre          string
	Apellido        string
	LugarNacimiento sql.NullString
	FechaNacimiento sql.NullString
	Nacionalidad    sql.NullString
	EstadoCivil     sql.NullString
	TipoDocumento   sql.NullString
	NroDocumento    string
	Profesion       sql.NullString
	LugarTrabajo    sql.NullString
	Domicilio       sql.NullString
	Telefono        sql.NullString
	Email           sql.NullString
	Estado          string
	Activo          int64
	FechaAprobacion sql.NullString
	Clasificacion   string
	TitularID       sql.NullInt64
	FechaCreacion   time.Time
}

type Token struct {
	ID            int64
	UsuarioID     int64
	Token         string
	Tipo          string
	Expiracion    time.Time
	FechaCreacion time.Time
}

type TransaccionesCaja struct {
	ID            int64
	Tipo          string
	Cuenta        string
	Monto         float64
	Fecha         string
	Categoria     string
	Descripcion   sql.NullString
	FechaCreacion time.Time
}

type TransaccionesCtaCte struct {
	ID                int64
	SocioID           int64
	Tipo              string
	Monto             float64
	Fecha             string
	Descripcion       sql.NullString
	TransaccionCajaID sql.NullInt64
}

type Usuario struct {
	ID            int64
	Email         string
	PasswordHash  string
	Rol           string
	Activo        sql.NullInt64
	Verificado    int64
	FechaCreacion time.Time
}

type ValoresCuotum struct {
	ID              int64
	Clasificacion   string
	Monto           float64
	VigenciaInicial string
	FechaCreacion   time.Time
}
