// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createCuotaGenerada = `-- name: CreateCuotaGenerada :one
INSERT INTO cuotas_generadas (socio_id, periodo, monto_original, monto_pendiente, estado)
VALUES (?, ?, ?, ?, ?)
RETURNING id, socio_id, periodo, monto_original, monto_pendiente, estado
`

type CreateCuotaGeneradaParams struct {
	SocioID        int64
	Periodo        string
	MontoOriginal  float64
	MontoPendiente float64
	Estado         string
}

// Cuotas Generadas Queries
func (q *Queries) CreateCuotaGenerada(ctx context.Context, arg CreateCuotaGeneradaParams) (CuotasGenerada, error) {
	row := q.db.QueryRowContext(ctx, createCuotaGenerada,
		arg.SocioID,
		arg.Periodo,
		arg.MontoOriginal,
		arg.MontoPendiente,
		arg.Estado,
	)
	var i CuotasGenerada
	err := row.Scan(
		&i.ID,
		&i.SocioID,
		&i.Periodo,
		&i.MontoOriginal,
		&i.MontoPendiente,
		&i.Estado,
	)
	return i, err
}

const createOrUpdateCuotaConfig = `-- name: CreateOrUpdateCuotaConfig :one
INSERT INTO cuotas_config (categoria, monto)
VALUES (?, ?)
ON CONFLICT(categoria) DO UPDATE SET monto = excluded.monto
RETURNING id, categoria, monto
`

type CreateOrUpdateCuotaConfigParams struct {
	Categoria string
	Monto     float64
}

// Cuotas Config Queries
func (q *Queries) CreateOrUpdateCuotaConfig(ctx context.Context, arg CreateOrUpdateCuotaConfigParams) (CuotasConfig, error) {
	row := q.db.QueryRowContext(ctx, createOrUpdateCuotaConfig, arg.Categoria, arg.Monto)
	var i CuotasConfig
	err := row.Scan(&i.ID, &i.Categoria, &i.Monto)
	return i, err
}

const createOrUpdateCuotaValor = `-- name: CreateOrUpdateCuotaValor :one
INSERT INTO valores_cuota (clasificacion, monto, vigencia_inicial)
VALUES (?, ?, ?)
ON CONFLICT(clasificacion, vigencia_inicial) DO UPDATE SET monto = excluded.monto
RETURNING id, clasificacion, monto, vigencia_inicial, fecha_creacion
`

type CreateOrUpdateCuotaValorParams struct {
	Clasificacion   string
	Monto           float64
	VigenciaInicial string
}

func (q *Queries) CreateOrUpdateCuotaValor(ctx context.Context, arg CreateOrUpdateCuotaValorParams) (ValoresCuotum, error) {
	row := q.db.QueryRowContext(ctx, createOrUpdateCuotaValor, arg.Clasificacion, arg.Monto, arg.VigenciaInicial)
	var i ValoresCuotum
	err := row.Scan(
		&i.ID,
		&i.Clasificacion,
		&i.Monto,
		&i.VigenciaInicial,
		&i.FechaCreacion,
	)
	return i, err
}

const createPagina = `-- name: CreatePagina :one
INSERT INTO paginas (titulo, slug, contenido, estado, visibilidad, autor_id)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, titulo, slug, contenido, estado, visibilidad, autor_id, fecha_actualizacion
`

type CreatePaginaParams struct {
	Titulo      string
	Slug        string
	Contenido   string
	Estado      string
	Visibilidad string
	AutorID     int64
}

// CMS / Paginas Queries
func (q *Queries) CreatePagina(ctx context.Context, arg CreatePaginaParams) (Pagina, error) {
	row := q.db.QueryRowContext(ctx, createPagina,
		arg.Titulo,
		arg.Slug,
		arg.Contenido,
		arg.Estado,
		arg.Visibilidad,
		arg.AutorID,
	)
	var i Pagina
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Slug,
		&i.Contenido,
		&i.Estado,
		&i.Visibilidad,
		&i.AutorID,
		&i.FechaActualizacion,
	)
	return i, err
}

const createSocio = `-- name: CreateSocio :one
INSERT INTO socios (
    nombre, apellido, lugar_nacimiento, fecha_nacimiento, nacionalidad,
    estado_civil, tipo_documento, nro_documento, profesion, lugar_trabajo,
    domicilio, telefono, email, estado, activo, numero_socio, fecha_aprobacion,
    clasificacion, titular_id
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, numero_socio, nombre, apellido, lugar_nacimiento, fecha_nacimiento, nacionalidad, estado_civil, tipo_documento, nro_documento, profesion, lugar_trabajo, domicilio, telefono, email, estado, activo, fecha_aprobacion, clasificacion, titular_id, fecha_creacion
`

type CreateSocioParams struct {
	Nombre          string
	Apellido        string
	LugarNacimiento sql.NullString
	FechaNacimiento sql.NullString
	Nacionalidad    sql.NullString
	EstadoCivil     sql.NullString
	TipoDocumento   sql.NullString
	NroDocumento    string
	Profesion       sql.NullString
	LugarTrabajo    sql.NullString
	Domicilio       sql.NullString
	Telefono        sql.NullString
	Email           sql.NullString
	Estado          string
	Activo          int64
	NumeroSocio     sql.NullString
	FechaAprobacion sql.NullString
	Clasificacion   string
	TitularID       sql.NullInt64
}

// Socios Queries
func (q *Queries) CreateSocio(ctx context.Context, arg CreateSocioParams) (Socio, error) {
	row := q.db.QueryRowContext(ctx, createSocio,
		arg.Nombre,
		arg.Apellido,
		arg.LugarNacimiento,
		arg.FechaNacimiento,
		arg.Nacionalidad,
		arg.EstadoCivil,
		arg.TipoDocumento,
		arg.NroDocumento,
		arg.Profesion,
		arg.LugarTrabajo,
		arg.Domicilio,
		arg.Telefono,
		arg.Email,
		arg.Estado,
		arg.Activo,
		arg.NumeroSocio,
		arg.FechaAprobacion,
		arg.Clasificacion,
		arg.TitularID,
	)
	var i Socio
	err := row.Scan(
		&i.ID,
		&i.NumeroSocio,
		&i.Nombre,
		&i.Apellido,
		&i.LugarNacimiento,
		&i.FechaNacimiento,
		&i.Nacionalidad,
		&i.EstadoCivil,
		&i.TipoDocumento,
		&i.NroDocumento,
		&i.Profesion,
		&i.LugarTrabajo,
		&i.Domicilio,
		&i.Telefono,
		&i.Email,
		&i.Estado,
		&i.Activo,
		&i.FechaAprobacion,
		&i.Clasificacion,
		&i.TitularID,
		&i.FechaCreacion,
	)
	return i, err
}

const createToken = `-- name: CreateToken :one
INSERT INTO tokens (usuario_id, token, tipo, expiracion)
VALUES (?, ?, ?, ?)
RETURNING id, usuario_id, token, tipo, expiracion, fecha_creacion
`

type CreateTokenParams struct {
	UsuarioID  int64
	Token      string
	Tipo       string
	Expiracion time.Time
}

// Tokens Queries
func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, createToken,
		arg.UsuarioID,
		arg.Token,
		arg.Tipo,
		arg.Expiracion,
	)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.Token,
		&i.Tipo,
		&i.Expiracion,
		&i.FechaCreacion,
	)
	return i, err
}

const createTransaccionCaja = `-- name: CreateTransaccionCaja :one
INSERT INTO transacciones_caja (tipo, cuenta, monto, fecha, categoria, descripcion)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, tipo, cuenta, monto, fecha, categoria, descripcion, fecha_creacion
`

type CreateTransaccionCajaParams struct {
	Tipo        string
	Cuenta      string
	Monto       float64
	Fecha       string
	Categoria   string
	Descripcion sql.NullString
}

// Caja / Tesoreria Queries
func (q *Queries) CreateTransaccionCaja(ctx context.Context, arg CreateTransaccionCajaParams) (TransaccionesCaja, error) {
	row := q.db.QueryRowContext(ctx, createTransaccionCaja,
		arg.Tipo,
		arg.Cuenta,
		arg.Monto,
		arg.Fecha,
		arg.Categoria,
		arg.Descripcion,
	)
	var i TransaccionesCaja
	err := row.Scan(
		&i.ID,
		&i.Tipo,
		&i.Cuenta,
		&i.Monto,
		&i.Fecha,
		&i.Categoria,
		&i.Descripcion,
		&i.FechaCreacion,
	)
	return i, err
}

const createTransaccionCtaCte = `-- name: CreateTransaccionCtaCte :one
INSERT INTO transacciones_cta_cte (socio_id, tipo, monto, fecha, descripcion, transaccion_caja_id)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, socio_id, tipo, monto, fecha, descripcion, transaccion_caja_id
`

type CreateTransaccionCtaCteParams struct {
	SocioID           int64
	Tipo              string
	Monto             float64
	Fecha             string
	Descripcion       sql.NullString
	TransaccionCajaID sql.NullInt64
}

// Cuenta Corriente Queries
func (q *Queries) CreateTransaccionCtaCte(ctx context.Context, arg CreateTransaccionCtaCteParams) (TransaccionesCtaCte, error) {
	row := q.db.QueryRowContext(ctx, createTransaccionCtaCte,
		arg.SocioID,
		arg.Tipo,
		arg.Monto,
		arg.Fecha,
		arg.Descripcion,
		arg.TransaccionCajaID,
	)
	var i TransaccionesCtaCte
	err := row.Scan(
		&i.ID,
		&i.SocioID,
		&i.Tipo,
		&i.Monto,
		&i.Fecha,
		&i.Descripcion,
		&i.TransaccionCajaID,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO usuarios (email, password_hash, rol, activo, verificado)
VALUES (?, ?, ?, ?, ?)
RETURNING id, email, password_hash, rol, activo, verificado, fecha_creacion
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	Rol          string
	Activo       sql.NullInt64
	Verificado   int64
}

// Usuarios Queries
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Rol,
		arg.Activo,
		arg.Verificado,
	)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Rol,
		&i.Activo,
		&i.Verificado,
		&i.FechaCreacion,
	)
	return i, err
}

const deletePagina = `-- name: DeletePagina :exec
DELETE FROM paginas WHERE id = ?
`

func (q *Queries) DeletePagina(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePagina, id)
	return err
}

const deleteToken = `-- name: DeleteToken :exec
DELETE FROM tokens WHERE id = ?
`

func (q *Queries) DeleteToken(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteToken, id)
	return err
}

const deleteTokensByUsuarioAndTipo = `-- name: DeleteTokensByUsuarioAndTipo :exec
DELETE FROM tokens WHERE usuario_id = ? AND tipo = ?
`

type DeleteTokensByUsuarioAndTipoParams struct {
	UsuarioID int64
	Tipo      string
}

func (q *Queries) DeleteTokensByUsuarioAndTipo(ctx context.Context, arg DeleteTokensByUsuarioAndTipoParams) error {
	_, err := q.db.ExecContext(ctx, deleteTokensByUsuarioAndTipo, arg.UsuarioID, arg.Tipo)
	return err
}

const getCajaBalanceByCuenta = `-- name: GetCajaBalanceByCuenta :one
SELECT CAST(COALESCE(SUM(CASE WHEN tipo = 'INGRESO' THEN monto ELSE -monto END), 0.0) AS REAL)
FROM transacciones_caja
WHERE cuenta = ?
`

func (q *Queries) GetCajaBalanceByCuenta(ctx context.Context, cuenta string) (float64, error) {
	row := q.db.QueryRowContext(ctx, getCajaBalanceByCuenta, cuenta)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const getCajaSummaryByCategory = `-- name: GetCajaSummaryByCategory :many
SELECT tipo, categoria, CAST(SUM(monto) AS REAL) as total
FROM transacciones_caja
GROUP BY tipo, categoria
ORDER BY tipo ASC, total DESC
`

type GetCajaSummaryByCategoryRow struct {
	Tipo      string
	Categoria string
	Total     float64
}

func (q *Queries) GetCajaSummaryByCategory(ctx context.Context) ([]GetCajaSummaryByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getCajaSummaryByCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCajaSummaryByCategoryRow
	for rows.Next() {
		var i GetCajaSummaryByCategoryRow
		if err := rows.Scan(&i.Tipo, &i.Categoria, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConfig = `-- name: GetConfig :one
SELECT valor FROM config WHERE clave = ? LIMIT 1
`

// Config Queries
func (q *Queries) GetConfig(ctx context.Context, clave string) (string, error) {
	row := q.db.QueryRowContext(ctx, getConfig, clave)
	var valor string
	err := row.Scan(&valor)
	return valor, err
}

const getCuotaConfigByCategoria = `-- name: GetCuotaConfigByCategoria :one
SELECT id, categoria, monto FROM cuotas_config WHERE categoria = ? LIMIT 1
`

func (q *Queries) GetCuotaConfigByCategoria(ctx context.Context, categoria string) (CuotasConfig, error) {
	row := q.db.QueryRowContext(ctx, getCuotaConfigByCategoria, categoria)
	var i CuotasConfig
	err := row.Scan(&i.ID, &i.Categoria, &i.Monto)
	return i, err
}

const getCuotaGeneradaBySocioAndPeriodo = `-- name: GetCuotaGeneradaBySocioAndPeriodo :one
SELECT id, socio_id, periodo, monto_original, monto_pendiente, estado FROM cuotas_generadas WHERE socio_id = ? AND periodo = ? LIMIT 1
`

type GetCuotaGeneradaBySocioAndPeriodoParams struct {
	SocioID int64
	Periodo string
}

func (q *Queries) GetCuotaGeneradaBySocioAndPeriodo(ctx context.Context, arg GetCuotaGeneradaBySocioAndPeriodoParams) (CuotasGenerada, error) {
	row := q.db.QueryRowContext(ctx, getCuotaGeneradaBySocioAndPeriodo, arg.SocioID, arg.Periodo)
	var i CuotasGenerada
	err := row.Scan(
		&i.ID,
		&i.SocioID,
		&i.Periodo,
		&i.MontoOriginal,
		&i.MontoPendiente,
		&i.Estado,
	)
	return i, err
}

const getCuotaValorByClasificacionAndPeriodo = `-- name: GetCuotaValorByClasificacionAndPeriodo :one
SELECT id, clasificacion, monto, vigencia_inicial, fecha_creacion
FROM valores_cuota
WHERE clasificacion = ? AND vigencia_inicial <= ?
ORDER BY vigencia_inicial DESC LIMIT 1
`

type GetCuotaValorByClasificacionAndPeriodoParams struct {
	Clasificacion   string
	VigenciaInicial string
}

// Valores Cuota Queries
func (q *Queries) GetCuotaValorByClasificacionAndPeriodo(ctx context.Context, arg GetCuotaValorByClasificacionAndPeriodoParams) (ValoresCuotum, error) {
	row := q.db.QueryRowContext(ctx, getCuotaValorByClasificacionAndPeriodo, arg.Clasificacion, arg.VigenciaInicial)
	var i ValoresCuotum
	err := row.Scan(
		&i.ID,
		&i.Clasificacion,
		&i.Monto,
		&i.VigenciaInicial,
		&i.FechaCreacion,
	)
	return i, err
}

const getLastNumeroSocio = `-- name: GetLastNumeroSocio :one
SELECT numero_socio FROM socios 
WHERE numero_socio IS NOT NULL AND numero_socio != ''
ORDER BY CAST(numero_socio AS INTEGER) DESC LIMIT 1
`

func (q *Queries) GetLastNumeroSocio(ctx context.Context) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getLastNumeroSocio)
	var numero_socio sql.NullString
	err := row.Scan(&numero_socio)
	return numero_socio, err
}

const getPaginaById = `-- name: GetPaginaById :one
SELECT id, titulo, slug, contenido, estado, visibilidad, autor_id, fecha_actualizacion FROM paginas WHERE id = ? LIMIT 1
`

func (q *Queries) GetPaginaById(ctx context.Context, id int64) (Pagina, error) {
	row := q.db.QueryRowContext(ctx, getPaginaById, id)
	var i Pagina
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Slug,
		&i.Contenido,
		&i.Estado,
		&i.Visibilidad,
		&i.AutorID,
		&i.FechaActualizacion,
	)
	return i, err
}

const getPaginaBySlug = `-- name: GetPaginaBySlug :one
SELECT id, titulo, slug, contenido, estado, visibilidad, autor_id, fecha_actualizacion FROM paginas WHERE slug = ? LIMIT 1
`

func (q *Queries) GetPaginaBySlug(ctx context.Context, slug string) (Pagina, error) {
	row := q.db.QueryRowContext(ctx, getPaginaBySlug, slug)
	var i Pagina
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Slug,
		&i.Contenido,
		&i.Estado,
		&i.Visibilidad,
		&i.AutorID,
		&i.FechaActualizacion,
	)
	return i, err
}

const getSaldoSocio = `-- name: GetSaldoSocio :one
SELECT CAST(COALESCE(SUM(CASE WHEN tipo = 'CREDITO' THEN monto ELSE 0 END) - 
                     SUM(CASE WHEN tipo = 'DEBITO' THEN monto ELSE 0 END), 0.0) AS REAL) AS saldo
FROM transacciones_cta_cte
WHERE socio_id = ?
`

func (q *Queries) GetSaldoSocio(ctx context.Context, socioID int64) (float64, error) {
	row := q.db.QueryRowContext(ctx, getSaldoSocio, socioID)
	var saldo float64
	err := row.Scan(&saldo)
	return saldo, err
}

const getSocioByDocumento = `-- name: GetSocioByDocumento :one
SELECT id, numero_socio, nombre, apellido, lugar_nacimiento, fecha_nacimiento, nacionalidad, estado_civil, tipo_documento, nro_documento, profesion, lugar_trabajo, domicilio, telefono, email, estado, activo, fecha_aprobacion, clasificacion, titular_id, fecha_creacion FROM socios WHERE nro_documento = ? LIMIT 1
`

func (q *Queries) GetSocioByDocumento(ctx context.Context, nroDocumento string) (Socio, error) {
	row := q.db.QueryRowContext(ctx, getSocioByDocumento, nroDocumento)
	var i Socio
	err := row.Scan(
		&i.ID,
		&i.NumeroSocio,
		&i.Nombre,
		&i.Apellido,
		&i.LugarNacimiento,
		&i.FechaNacimiento,
		&i.Nacionalidad,
		&i.EstadoCivil,
		&i.TipoDocumento,
		&i.NroDocumento,
		&i.Profesion,
		&i.LugarTrabajo,
		&i.Domicilio,
		&i.Telefono,
		&i.Email,
		&i.Estado,
		&i.Activo,
		&i.FechaAprobacion,
		&i.Clasificacion,
		&i.TitularID,
		&i.FechaCreacion,
	)
	return i, err
}

const getSocioByEmail = `-- name: GetSocioByEmail :one
SELECT id, numero_socio, nombre, apellido, lugar_nacimiento, fecha_nacimiento, nacionalidad, estado_civil, tipo_documento, nro_documento, profesion, lugar_trabajo, domicilio, telefono, email, estado, activo, fecha_aprobacion, clasificacion, titular_id, fecha_creacion FROM socios WHERE email = ? LIMIT 1
`

func (q *Queries) GetSocioByEmail(ctx context.Context, email sql.NullString) (Socio, error) {
	row := q.db.QueryRowContext(ctx, getSocioByEmail, email)
	var i Socio
	err := row.Scan(
		&i.ID,
		&i.NumeroSocio,
		&i.Nombre,
		&i.Apellido,
		&i.LugarNacimiento,
		&i.FechaNacimiento,
		&i.Nacionalidad,
		&i.EstadoCivil,
		&i.TipoDocumento,
		&i.NroDocumento,
		&i.Profesion,
		&i.LugarTrabajo,
		&i.Domicilio,
		&i.Telefono,
		&i.Email,
		&i.Estado,
		&i.Activo,
		&i.FechaAprobacion,
		&i.Clasificacion,
		&i.TitularID,
		&i.FechaCreacion,
	)
	return i, err
}

const getSocioById = `-- name: GetSocioById :one
SELECT id, numero_socio, nombre, apellido, lugar_nacimiento, fecha_nacimiento, nacionalidad, estado_civil, tipo_documento, nro_documento, profesion, lugar_trabajo, domicilio, telefono, email, estado, activo, fecha_aprobacion, clasificacion, titular_id, fecha_creacion FROM socios WHERE id = ? LIMIT 1
`

func (q *Queries) GetSocioById(ctx context.Context, id int64) (Socio, error) {
	row := q.db.QueryRowContext(ctx, getSocioById, id)
	var i Socio
	err := row.Scan(
		&i.ID,
		&i.NumeroSocio,
		&i.Nombre,
		&i.Apellido,
		&i.LugarNacimiento,
		&i.FechaNacimiento,
		&i.Nacionalidad,
		&i.EstadoCivil,
		&i.TipoDocumento,
		&i.NroDocumento,
		&i.Profesion,
		&i.LugarTrabajo,
		&i.Domicilio,
		&i.Telefono,
		&i.Email,
		&i.Estado,
		&i.Activo,
		&i.FechaAprobacion,
		&i.Clasificacion,
		&i.TitularID,
		&i.FechaCreacion,
	)
	return i, err
}

const getTokenByValueAndTipo = `-- name: GetTokenByValueAndTipo :one
SELECT id, usuario_id, token, tipo, expiracion, fecha_creacion
FROM tokens
WHERE token = ? AND tipo = ? LIMIT 1
`

type GetTokenByValueAndTipoParams struct {
	Token string
	Tipo  string
}

func (q *Queries) GetTokenByValueAndTipo(ctx context.Context, arg GetTokenByValueAndTipoParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, getTokenByValueAndTipo, arg.Token, arg.Tipo)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.Token,
		&i.Tipo,
		&i.Expiracion,
		&i.FechaCreacion,
	)
	return i, err
}

const getTotalEgresosCaja = `-- name: GetTotalEgresosCaja :one
SELECT CAST(COALESCE(SUM(monto), 0.0) AS REAL) FROM transacciones_caja WHERE tipo = 'EGRESO'
`

func (q *Queries) GetTotalEgresosCaja(ctx context.Context) (float64, error) {
	row := q.db.QueryRowContext(ctx, getTotalEgresosCaja)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const getTotalIngresosCaja = `-- name: GetTotalIngresosCaja :one
SELECT CAST(COALESCE(SUM(monto), 0.0) AS REAL) FROM transacciones_caja WHERE tipo = 'INGRESO'
`

func (q *Queries) GetTotalIngresosCaja(ctx context.Context) (float64, error) {
	row := q.db.QueryRowContext(ctx, getTotalIngresosCaja)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, rol, activo, verificado, fecha_creacion FROM usuarios WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Rol,
		&i.Activo,
		&i.Verificado,
		&i.FechaCreacion,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, email, password_hash, rol, activo, verificado, fecha_creacion FROM usuarios WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id int64) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Rol,
		&i.Activo,
		&i.Verificado,
		&i.FechaCreacion,
	)
	return i, err
}

const listCuotasConfig = `-- name: ListCuotasConfig :many
SELECT id, categoria, monto FROM cuotas_config
`

func (q *Queries) ListCuotasConfig(ctx context.Context) ([]CuotasConfig, error) {
	rows, err := q.db.QueryContext(ctx, listCuotasConfig)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CuotasConfig
	for rows.Next() {
		var i CuotasConfig
		if err := rows.Scan(&i.ID, &i.Categoria, &i.Monto); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCuotasGeneradasBySocio = `-- name: ListCuotasGeneradasBySocio :many
SELECT id, socio_id, periodo, monto_original, monto_pendiente, estado FROM cuotas_generadas WHERE socio_id = ? ORDER BY periodo DESC
`

func (q *Queries) ListCuotasGeneradasBySocio(ctx context.Context, socioID int64) ([]CuotasGenerada, error) {
	rows, err := q.db.QueryContext(ctx, listCuotasGeneradasBySocio, socioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CuotasGenerada
	for rows.Next() {
		var i CuotasGenerada
		if err := rows.Scan(
			&i.ID,
			&i.SocioID,
			&i.Periodo,
			&i.MontoOriginal,
			&i.MontoPendiente,
			&i.Estado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCuotasValores = `-- name: ListCuotasValores :many
SELECT id, clasificacion, monto, vigencia_inicial, fecha_creacion
FROM valores_cuota
ORDER BY clasificacion ASC, vigencia_inicial DESC
`

func (q *Queries) ListCuotasValores(ctx context.Context) ([]ValoresCuotum, error) {
	rows, err := q.db.QueryContext(ctx, listCuotasValores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ValoresCuotum
	for rows.Next() {
		var i ValoresCuotum
		if err := rows.Scan(
			&i.ID,
			&i.Clasificacion,
			&i.Monto,
			&i.VigenciaInicial,
			&i.FechaCreacion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaginas = `-- name: ListPaginas :many
SELECT id, titulo, slug, contenido, estado, visibilidad, autor_id, fecha_actualizacion FROM paginas ORDER BY fecha_actualizacion DESC
`

func (q *Queries) ListPaginas(ctx context.Context) ([]Pagina, error) {
	rows, err := q.db.QueryContext(ctx, listPaginas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pagina
	for rows.Next() {
		var i Pagina
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Slug,
			&i.Contenido,
			&i.Estado,
			&i.Visibilidad,
			&i.AutorID,
			&i.FechaActualizacion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSocios = `-- name: ListSocios :many
SELECT id, numero_socio, nombre, apellido, lugar_nacimiento, fecha_nacimiento, nacionalidad, estado_civil, tipo_documento, nro_documento, profesion, lugar_trabajo, domicilio, telefono, email, estado, activo, fecha_aprobacion, clasificacion, titular_id, fecha_creacion FROM socios ORDER BY id DESC
`

func (q *Queries) ListSocios(ctx context.Context) ([]Socio, error) {
	rows, err := q.db.QueryContext(ctx, listSocios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Socio
	for rows.Next() {
		var i Socio
		if err := rows.Scan(
			&i.ID,
			&i.NumeroSocio,
			&i.Nombre,
			&i.Apellido,
			&i.LugarNacimiento,
			&i.FechaNacimiento,
			&i.Nacionalidad,
			&i.EstadoCivil,
			&i.TipoDocumento,
			&i.NroDocumento,
			&i.Profesion,
			&i.LugarTrabajo,
			&i.Domicilio,
			&i.Telefono,
			&i.Email,
			&i.Estado,
			&i.Activo,
			&i.FechaAprobacion,
			&i.Clasificacion,
			&i.TitularID,
			&i.FechaCreacion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransaccionesCaja = `-- name: ListTransaccionesCaja :many
SELECT id, tipo, cuenta, monto, fecha, categoria, descripcion, fecha_creacion
FROM transacciones_caja
ORDER BY fecha DESC, id DESC LIMIT 1000000
`

func (q *Queries) ListTransaccionesCaja(ctx context.Context) ([]TransaccionesCaja, error) {
	rows, err := q.db.QueryContext(ctx, listTransaccionesCaja)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransaccionesCaja
	for rows.Next() {
		var i TransaccionesCaja
		if err := rows.Scan(
			&i.ID,
			&i.Tipo,
			&i.Cuenta,
			&i.Monto,
			&i.Fecha,
			&i.Categoria,
			&i.Descripcion,
			&i.FechaCreacion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransaccionesCtaCteBySocio = `-- name: ListTransaccionesCtaCteBySocio :many
SELECT id, socio_id, tipo, monto, fecha, descripcion, transaccion_caja_id FROM transacciones_cta_cte WHERE socio_id = ? ORDER BY fecha DESC, id DESC
`

func (q *Queries) ListTransaccionesCtaCteBySocio(ctx context.Context, socioID int64) ([]TransaccionesCtaCte, error) {
	rows, err := q.db.QueryContext(ctx, listTransaccionesCtaCteBySocio, socioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransaccionesCtaCte
	for rows.Next() {
		var i TransaccionesCtaCte
		if err := rows.Scan(
			&i.ID,
			&i.SocioID,
			&i.Tipo,
			&i.Monto,
			&i.Fecha,
			&i.Descripcion,
			&i.TransaccionCajaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, rol, activo, verificado, fecha_creacion FROM usuarios ORDER BY fecha_creacion DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]Usuario, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Usuario
	for rows.Next() {
		var i Usuario
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Rol,
			&i.Activo,
			&i.Verificado,
			&i.FechaCreacion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setConfig = `-- name: SetConfig :exec
INSERT INTO config (clave, valor) VALUES (?, ?)
ON CONFLICT(clave) DO UPDATE SET valor = excluded.valor
`

type SetConfigParams struct {
	Clave string
	Valor string
}

func (q *Queries) SetConfig(ctx context.Context, arg SetConfigParams) error {
	_, err := q.db.ExecContext(ctx, setConfig, arg.Clave, arg.Valor)
	return err
}

const updateCuotaGeneradaMontoPendiente = `-- name: UpdateCuotaGeneradaMontoPendiente :exec
UPDATE cuotas_generadas 
SET monto_pendiente = ?, estado = ? 
WHERE id = ?
`

type UpdateCuotaGeneradaMontoPendienteParams struct {
	MontoPendiente float64
	Estado         string
	ID             int64
}

func (q *Queries) UpdateCuotaGeneradaMontoPendiente(ctx context.Context, arg UpdateCuotaGeneradaMontoPendienteParams) error {
	_, err := q.db.ExecContext(ctx, updateCuotaGeneradaMontoPendiente, arg.MontoPendiente, arg.Estado, arg.ID)
	return err
}

const updatePagina = `-- name: UpdatePagina :exec
UPDATE paginas
SET titulo = ?, slug = ?, contenido = ?, estado = ?, visibilidad = ?, fecha_actualizacion = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdatePaginaParams struct {
	Titulo      string
	Slug        string
	Contenido   string
	Estado      string
	Visibilidad string
	ID          int64
}

func (q *Queries) UpdatePagina(ctx context.Context, arg UpdatePaginaParams) error {
	_, err := q.db.ExecContext(ctx, updatePagina,
		arg.Titulo,
		arg.Slug,
		arg.Contenido,
		arg.Estado,
		arg.Visibilidad,
		arg.ID,
	)
	return err
}

const updateSocio = `-- name: UpdateSocio :exec
UPDATE socios
SET nombre = ?, apellido = ?, lugar_nacimiento = ?, fecha_nacimiento = ?, 
    nacionalidad = ?, estado_civil = ?, tipo_documento = ?, nro_documento = ?, 
    profesion = ?, lugar_trabajo = ?, domicilio = ?, telefono = ?, email = ?,
    clasificacion = ?, titular_id = ?
WHERE id = ?
`

type UpdateSocioParams struct {
	Nombre          string
	Apellido        string
	LugarNacimiento sql.NullString
	FechaNacimiento sql.NullString
	Nacionalidad    sql.NullString
	EstadoCivil     sql.NullString
	TipoDocumento   sql.NullString
	NroDocumento    string
	Profesion       sql.NullString
	LugarTrabajo    sql.NullString
	Domicilio       sql.NullString
	Telefono        sql.NullString
	Email           sql.NullString
	Clasificacion   string
	TitularID       sql.NullInt64
	ID              int64
}

func (q *Queries) UpdateSocio(ctx context.Context, arg UpdateSocioParams) error {
	_, err := q.db.ExecContext(ctx, updateSocio,
		arg.Nombre,
		arg.Apellido,
		arg.LugarNacimiento,
		arg.FechaNacimiento,
		arg.Nacionalidad,
		arg.EstadoCivil,
		arg.TipoDocumento,
		arg.NroDocumento,
		arg.Profesion,
		arg.LugarTrabajo,
		arg.Domicilio,
		arg.Telefono,
		arg.Email,
		arg.Clasificacion,
		arg.TitularID,
		arg.ID,
	)
	return err
}

const updateSocioActive = `-- name: UpdateSocioActive :exec
UPDATE socios SET activo = ? WHERE id = ?
`

type UpdateSocioActiveParams struct {
	Activo int64
	ID     int64
}

func (q *Queries) UpdateSocioActive(ctx context.Context, arg UpdateSocioActiveParams) error {
	_, err := q.db.ExecContext(ctx, updateSocioActive, arg.Activo, arg.ID)
	return err
}

const updateSocioStatus = `-- name: UpdateSocioStatus :exec
UPDATE socios 
SET estado = ?, numero_socio = ?, fecha_aprobacion = ? 
WHERE id = ?
`

type UpdateSocioStatusParams struct {
	Estado          string
	NumeroSocio     sql.NullString
	FechaAprobacion sql.NullString
	ID              int64
}

func (q *Queries) UpdateSocioStatus(ctx context.Context, arg UpdateSocioStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSocioStatus,
		arg.Estado,
		arg.NumeroSocio,
		arg.FechaAprobacion,
		arg.ID,
	)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE usuarios SET password_hash = ? WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash string
	ID           int64
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE usuarios SET rol = ? WHERE id = ?
`

type UpdateUserRoleParams struct {
	Rol string
	ID  int64
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateUserRole, arg.Rol, arg.ID)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE usuarios SET activo = ? WHERE id = ?
`

type UpdateUserStatusParams struct {
	Activo sql.NullInt64
	ID     int64
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStatus, arg.Activo, arg.ID)
	return err
}

const updateUserVerification = `-- name: UpdateUserVerification :exec
UPDATE usuarios SET verificado = ? WHERE id = ?
`

type UpdateUserVerificationParams struct {
	Verificado int64
	ID         int64
}

func (q *Queries) UpdateUserVerification(ctx context.Context, arg UpdateUserVerificationParams) error {
	_, err := q.db.ExecContext(ctx, updateUserVerification, arg.Verificado, arg.ID)
	return err
}
